# SPDX-FileCopyrightText: 2023 Stoney Jackson <dr.stoney@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

tasks:
  - name: Install PLCC
    before: echo "Installing PLCC into $HOME/plcc"
    init: source ./.gitpod/install-plcc.sh
